# Generated by Django 5.0.7 on 2024-07-25 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('key_manager', '0002_alter_customuser_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterModelTable(
            name='customuser',
            table=None,
        ),
    ]
